.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PIGZ 1 "January  3, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pigz \- compress or expand files
.SH SYNOPSIS
.B pigz
.RI [ options ] " files" ...
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBpigz\fP is an almost compatible replacement for the 
.B gzip
program providing a common set of command line arguments. The special feature
of pigz is support for (de)compression execution in multiple
threads, utilizing more available CPU power on multicore or multiprocessor
systems than the standard gzip implementation.
.SH OPTIONS
These program follows the usual GNU command line syntax, with long
options starting with two dashes (`-'). Most options are derived from the 
.B gzip 
program, see its documentation for details. There are also new pigz specific
options for advanced usage which are displayed in program's help output.
.SH SEE ALSO
.BR gzip (1)
.br
.PP
This manual page was written by Eduard Bloch <blade@debian.org>,
for the Debian project (and may be used by others).
